<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\  EntityRepository
{
    public function findNewsByCategory(array $categoriesID)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Article a WHERE a.categoryID IN(:categoriesID)'
            )
            ->setParameter('categoriesID', $categoriesID)
            ->getResult();
    }
}
