<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\  EntityRepository
{
    public function findNewsByCategory(array $categoriesID)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Article a WHERE a.category IN(:categoriesID)'
            )
            ->setParameter('categoriesID', $categoriesID)
            ->getResult();
    }

    public function findNewsById(int $id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT article, similar 
                      FROM 
                        AppBundle:Article article 
                      LEFT JOIN 
                        article.similarArticles similar
                      WHERE 
                        article.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}