<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGeneralCategories()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Category c WHERE c.parent is null'
            )
            ->getResult();
    }

    public function getSimilarCategories(string $similar,int $maxLevel)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Category c WHERE c.level != :lev AND c.name LIKE :similar'
            )
            ->setParameter('lev', $maxLevel)
            ->setParameter('similar', '%' . $similar . '%')
            ->setMaxResults(5)
            ->getResult();
    }

    public function getCategoriesList(string $sortField, bool $isAscending, array $filters, int $offset, int $itemsPerPage): array
    {
        $query = 'SELECT c FROM AppBundle:Category c';
        return $this->getSortedAndFilteredCategories($query, $sortField, $isAscending, $filters)
            ->setFirstResult($offset)
            ->setMaxResults($itemsPerPage)
            ->getResult();
    }

    public function getCategoriesCount(string $sortField, bool $isAscending, array $filters): int
    {
        $query = 'SELECT COUNT(c) FROM AppBundle:Category c';
        return $this->getSortedAndFilteredCategories($query, $sortField, $isAscending, $filters)
            ->getSingleScalarResult();
    }

    private function getSortedAndFilteredCategories(string $query, string $sortField, bool $isAscending, array $filters): Query
    {
        $query .= $this->getDQLWithFilters($filters);
        $query .= ' ORDER BY c.' . $sortField . ' ' . ($isAscending ? 'ASC' : 'DESC');

        $temp = [];
        for ($i = 0; $i < count($filters); $i++) {
            $temp[$i] = $filters[$i][1];
        }

        return $this->getEntityManager()
            ->createQuery($query)
            ->setParameters($temp);
    }

    private function getDQLWithFilters(array $filters): string
    {
        $result = '';
        if (key_exists(0, $filters)) {
            $result = ' WHERE c.' . $filters[0][0] . ' = ?0';
            for ($i = 1; $i < count($filters); $i++) {
                $result .= ' AND c.' . $filters[$i][0] . ' = ' . '?' . $i;
            }
        }
        return $result;
    }
}
