<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array|null
     */
    public function findGeneralCategories(): ?array
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Category c WHERE c.parent is null'
            )
            ->getResult();
    }

    /**
     * @param string $similar
     * @param int $maxLevel
     * @return array|null
     */
    public function getSimilarCategories(string $similar, int $maxLevel): ?array
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Category c WHERE c.level != :lev AND c.name LIKE :similar'
            )
            ->setParameter('lev', $maxLevel)
            ->setParameter('similar', '%' . $similar . '%')
            ->setMaxResults(5)
            ->getResult();
    }

    /**
     * @param string $sortField
     * @param bool $isAscending
     * @param array $filters
     * @param int $offset
     * @param int $itemsPerPage
     * @return array|null
     */
    public function getCategoriesList(string $sortField, bool $isAscending, array $filters, int $offset, int $itemsPerPage): ?array
    {
        $query = 'SELECT c FROM AppBundle:Category c';
        return $this->getSortedAndFilteredCategories($query, $sortField, $isAscending, $filters)
            ->setFirstResult($offset)
            ->setMaxResults($itemsPerPage)
            ->getResult();
    }

    /**
     * @param string $sortField
     * @param bool $isAscending
     * @param array $filters
     * @return int
     */
    public function getCategoriesCount(string $sortField, bool $isAscending, array $filters): int
    {
        $query = 'SELECT COUNT(c) FROM AppBundle:Category c';
        return $this->getSortedAndFilteredCategories($query, $sortField, $isAscending, $filters)
            ->getSingleScalarResult();
    }

    /**
     * @param int $id
     * @return array|null
     */
    public function findCategoryById(int $id): ?array
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT category, articles, children 
                      FROM 
                        AppBundle:Category category 
                      LEFT JOIN 
                        category.articles articles
                      LEFT JOIN 
                        category.children children
                      WHERE 
                        category.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }

    /**
     * @param string $query
     * @param string $sortField
     * @param bool $isAscending
     * @param array $filters
     * @return Query
     */
    private function getSortedAndFilteredCategories(string $query, string $sortField, bool $isAscending, array $filters): Query
    {
        $query .= $this->getDQLWithFilters($filters);
        $query .= ' ORDER BY c.' . $sortField . ' ' . ($isAscending ? 'ASC' : 'DESC');

        $temp = [];
        for ($i = 0; $i < count($filters); $i++) {
            $temp[$i] = $filters[$i][1];
        }

        return $this->getEntityManager()
            ->createQuery($query)
            ->setParameters($temp);
    }

    /**
     * @param array $filters
     * @return string
     */
    private function getDQLWithFilters(array $filters): string
    {
        $result = '';
        if (key_exists(0, $filters)) {
            $result = ' WHERE c.' . $filters[0][0] . ' = ?0';
            for ($i = 1; $i < count($filters); $i++) {
                $result .= ' AND c.' . $filters[$i][0] . ' = ' . '?' . $i;
            }
        }
        return $result;
    }
}
