<?php

namespace AppBundle\Repository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $type
     * @return int
     */
    public function getSubscribedUsersCount(string $type): int
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(s) FROM AppBundle:Subscription s
                          WHERE s.type = :type'
            )
            ->setParameter('type', $type)
            ->getSingleScalarResult();
    }

    /**
     * @param string $type
     * @param int $offset
     * @param int $rowsPerRequest
     * @return array|null
     */
    public function getSubscribedUsers(string $type, int $offset, int $rowsPerRequest): ?array
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT subscr, user 
                      FROM 
                        AppBundle:Subscription subscr
                      LEFT JOIN
                        subscr.userID user
                      WHERE 
                        subscr.type = :type'
            )
            ->setParameter('type', $type)
            ->setFirstResult($offset)
            ->setMaxResults($rowsPerRequest)
            ->getResult();
    }
}
